group = "com.serenegiant.uvc_manager"
version = "1.0-SNAPSHOT"

buildscript {
    ext.kotlin_version = "1.8.22"
    repositories {
        google()
        mavenCentral()
        mavenLocal()
    }

    dependencies {
        classpath("com.android.tools.build:gradle:8.7.0")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version")
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: "com.android.library"
apply plugin: "kotlin-android"

android {
    namespace = "com.serenegiant.uvc_manager"

    compileSdk = 35
    ndkVersion = "25.1.8937393"

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11
    }

    sourceSets {
        main.java.srcDirs += "src/main/kotlin"
        test.java.srcDirs += "src/test/kotlin"
    }

    defaultConfig {
        minSdk = 21
    }

    dependencies {
        testImplementation("org.jetbrains.kotlin:kotlin-test")
        testImplementation("org.mockito:mockito-core:5.1.0")
        implementation("com.serenegiant:common:9.8.2")
        // XXX example側のaarを参照する...
        //     プラグイン側でローカルaarとして取り込んで、example画家へダミーのmavenレポジトリとして
        //     アクセスできるように設定すると、Androidのプロジェクトとして開けばビルド・実行可能だけど、
        //     Flutterのプロジェクトとして開いてmain.dartを実行しようとすると現行のFlutter SDKでは
        //     エラーになってビルドできないので仕方なくexample側へモジュールとしてaarをインポートして
        //     プラグイン側から参照するようにした。
        implementation project(":aandusb-release")
        implementation project(":flutter-uvc-plugin-release")
    }

    testOptions {
        unitTests.all {
            useJUnitPlatform()

            testLogging {
               events "passed", "skipped", "failed", "standardOut", "standardError"
               outputs.upToDateWhen {false}
               showStandardStreams = true
            }
        }
    }
}
